/**
 * Prompt construction for content-QC analysis. This tool audits content
 * QUALITY for a QC team — it is NOT a student aid. Prompts therefore focus on
 * defects, answer-key integrity, clarity, distractor strength, difficulty
 * calibration, and syllabus alignment — never on "how to teach the student".
 */

export const QC_OUTPUT_CONTRACT = `Return ONLY a raw JSON object (no markdown fences) with EXACTLY this shape:
{
  "structure": { "valid": boolean, "issues": string[] },
  "keyIntegrity": {
    "hasMarkedKey": boolean,
    "markedKey": string,
    "modelAnswer": string,          // the option letter YOU judge correct
    "agreesWithKey": boolean,
    "confidence": number,           // 0-100
    "rationale": string
  },
  "clarity": { "score": number, "issues": string[] },      // 0-100, higher = clearer
  "distractors": {
    "score": number,                // 0-100, higher = stronger distractors
    "perOption": [ { "key": string, "role": "correct"|"strong"|"weak"|"implausible"|"overlapping", "note": string } ]
  },
  "difficulty": { "level": "Easy"|"Medium"|"Hard", "score": number, "rationale": string },
  "alignment": { "topic": string, "subtopic": string, "onSyllabus": boolean, "score": number },
  "flags": string[],                // e.g. "answer-key-mismatch","ambiguous-stem","duplicate-answer","grammar","factual-error"
  "verdict": { "status": "pass"|"review"|"fail", "score": number, "summary": string },
  "fixes": string[]                 // concrete edit suggestions for the content team
}`;

export function buildQcSystemPrompt(exam, rubricText) {
  return `You are a senior content quality-control auditor for high-stakes competitive-exam material${
    exam ? ` in the "${exam.name}" vertical` : ''
  }. Your audience is the internal content team, not students.

Your job: detect defects and score quality so a reviewer can accept, revise, or reject each item. Be rigorous and skeptical. Verify the marked answer key yourself against the stem and options; if the key is wrong or the question is unanswerable/ambiguous, say so plainly.

Judge against these dimensions: structural validity, answer-key integrity, wording clarity (ambiguity, double negatives, grammar), distractor strength (plausible-but-wrong vs. giveaway or overlapping), difficulty calibration, and syllabus alignment.

${rubricText ? `Team quality rubric for this vertical:\n${rubricText}\n` : ''}
${QC_OUTPUT_CONTRACT}`;
}

function renderQuestion(q) {
  const opts = (q.options || []).map((o) => `(${o.key}) ${o.text}`).join('\n');
  return `${q.passage ? `PASSAGE/CONTEXT:\n${q.passage}\n\n` : ''}QUESTION:\n${q.stem}\n\nOPTIONS:\n${opts || '(none parsed)'}\n\nMARKED ANSWER KEY: ${q.answerKey || '(none)'}`;
}

function renderExemplars(exemplars) {
  if (!exemplars || exemplars.length === 0) return '';
  const blocks = exemplars
    .map(
      (e, i) =>
        `Exemplar ${i + 1} (QC verdict: ${e.verdict}${e.notes ? `; note: ${e.notes}` : ''}):\n${
          e.passage ? e.passage + '\n' : ''
        }${e.stem}\n${(e.options || []).map((o) => `(${o.key}) ${o.text}`).join('\n')}\nKey: ${e.answerKey}`,
    )
    .join('\n\n');
  return `\nThe QC team has APPROVED these reference items for this vertical. Use them to calibrate topic, tone, difficulty and acceptable phrasing:\n${blocks}\n`;
}

export function buildQcUserPrompt(question, exemplars) {
  return `Audit the following item.${renderExemplars(exemplars)}
ITEM UNDER AUDIT:
${renderQuestion(question)}`;
}

// ── AI-vs-human detection ─────────────────────────────────────────────
export const DETECT_OUTPUT_CONTRACT = `Return ONLY raw JSON (no fences):
{
  "aiLikelihood": number,          // 0-100 probability the text is AI-generated
  "verdict": "Human"|"Likely Human"|"Uncertain"|"Likely AI"|"AI-generated",
  "confidence": number,            // 0-100
  "signals": string[],             // concrete evidence (phrasing, uniformity, etc.)
  "humanSignals": string[],
  "rationale": string
}`;

export function buildDetectSystemPrompt() {
  return `You are a forensic linguist auditing whether exam/content text was written by a human subject-matter expert or generated by an AI language model. The content team needs to know if vendors are submitting AI-generated material.

Weigh: burstiness (sentence-length variation), perplexity/predictability, over-use of formulaic transitions ("moreover", "furthermore", "it is important to note"), uniform paragraph scaffolding, generic hedging, and absence of domain-specific idiosyncrasy or genuine expertise. Human expert writing tends to be uneven, specific, occasionally idiosyncratic, and densely technical.

Be calibrated: do not call clean professional writing "AI" without positive AI signals.

${DETECT_OUTPUT_CONTRACT}`;
}

export function buildDetectUserPrompt(text) {
  return `Analyse this text:\n---\n${text.slice(0, 12000)}\n---`;
}
