import React, { useState, useEffect, useCallback } from 'react';
import Sidebar from './components/Sidebar';
import Dashboard from './components/Dashboard';
import AnalyzeView from './components/AnalyzeView';
import DetectorView from './components/DetectorView';
import ModelsView from './components/ModelsView';
import SettingsView from './components/SettingsView';
import { ToastProvider } from './components/ui';
import { api } from './api';

const HEADERS = {
  dashboard: ['Dashboard', 'Quality overview across every analysed document and content vertical.'],
  analyze: ['Analyze Content', 'Upload a paper or DPP and run the QC audit — parsing, key integrity, clarity and distractor checks.'],
  detector: ['AI Content Detector', 'Determine whether submitted content was written by a human expert or generated by an AI model.'],
  models: ['Models & Training', 'One model per content vertical — LoRA fine-tuning with local LLAMA inference.'],
  settings: ['Settings', 'LLAMA service status and local inference configuration.'],
};

export default function App() {
  const [view, setView] = useState('dashboard');
  const [theme, setTheme] = useState(() => localStorage.getItem('qc_theme') || 'dark');
  const [capabilities, setCapabilities] = useState(null);
  const [exams, setExams] = useState([]);
  const [analyses, setAnalyses] = useState([]);
  const [booted, setBooted] = useState(false);
  const [serverDown, setServerDown] = useState(false);

  useEffect(() => {
    document.documentElement.classList.toggle('light', theme === 'light');
    localStorage.setItem('qc_theme', theme);
  }, [theme]);

  const refreshExams = useCallback(async () => {
    const e = await api.listExams();
    setExams(e);
    return e;
  }, []);

  const refreshAnalyses = useCallback(async () => {
    const a = await api.listAnalyses();
    setAnalyses(a);
    return a;
  }, []);

  useEffect(() => {
    (async () => {
      try {
        const sys = await api.system();
        setCapabilities(sys.capabilities);
        await Promise.all([refreshExams(), refreshAnalyses()]);
      } catch {
        setServerDown(true);
      } finally {
        setBooted(true);
      }
    })();
  }, [refreshExams, refreshAnalyses]);

  const [title, subtitle] = HEADERS[view] || ['', ''];

  const shared = { capabilities, exams, analyses, refreshExams, refreshAnalyses, onNavigate: setView };

  return (
    <ToastProvider>
      <div className="app-shell">
        <Sidebar
          active={view}
          onNavigate={setView}
          theme={theme}
          onToggleTheme={() => setTheme((t) => (t === 'dark' ? 'light' : 'dark'))}
          examCount={exams.length}
        />
        <div className="main">
          <div className="topbar">
            <div>
              <h1>{title}</h1>
              <p>{subtitle}</p>
            </div>
          </div>

          <div className="view">
            {serverDown ? (
              <div className="card">
                <h3>Backend not reachable</h3>
                <p className="muted" style={{ marginTop: 8 }}>
                  The QC server isn't responding. Start it with{' '}
                  <code>cd server &amp;&amp; npm run dev</code> and reload. The API is expected at{' '}
                  <code>http://localhost:8787</code> (proxied via <code>/api</code>).
                </p>
              </div>
            ) : !booted ? (
              <div className="stat-grid">
                {[0, 1, 2, 3].map((i) => <div key={i} className="skeleton" style={{ height: 108 }} />)}
              </div>
            ) : (
              <>
                {view === 'dashboard' && <Dashboard {...shared} />}
                {view === 'analyze' && <AnalyzeView {...shared} />}
                {view === 'detector' && <DetectorView {...shared} />}
                {view === 'models' && <ModelsView {...shared} />}
                {view === 'settings' && <SettingsView {...shared} />}
              </>
            )}
          </div>
        </div>
      </div>
    </ToastProvider>
  );
}
